return {}

-- local utils = require("core.utils")
-- local get_icon = utils.get_icon
--
-- local setup = {
--   auto_clean_after_session_restore = true,
--   auto_expand_width = true,
--   close_if_last_window = true,
--   enable_diagnostics = true,
--   enable_git_status = true,
--   sort_case_insensitive = true,
--   sources = { "filesystem", "buffers", "git_status" },
--   source_selector = {
--     winbar = true,
--     content_layout = "center",
--     sources = {
--       { source = "filesystem",  display_name = get_icon("FolderClosed", 1) .. "File" },
--       { source = "buffers",     display_name = get_icon("DefaultFile", 1) .. "Bufs" },
--       { source = "git_status",  display_name = get_icon("Git", 1) .. "Git" },
--       { source = "diagnostics", display_name = get_icon("Diagnostic", 1) .. "Diagnostic" },
--     },
--   },
--   default_component_configs = {
--     indent = { padding = 0 },
--     icon = {
--       folder_closed = get_icon "FolderClosed",
--       folder_open = get_icon "FolderOpen",
--       folder_empty = get_icon "FolderEmpty",
--       folder_empty_open = get_icon "FolderEmpty",
--       default = get_icon "DefaultFile",
--     },
--     modified = { symbol = get_icon "FileModified" },
--     git_status = {
--       symbols = {
--         added = get_icon "GitAdd",
--         deleted = get_icon "GitDelete",
--         modified = get_icon "GitChange",
--         renamed = get_icon "GitRenamed",
--         untracked = get_icon "GitUntracked",
--         ignored = get_icon "GitIgnored",
--         unstaged = get_icon "GitUnstaged",
--         staged = get_icon "GitStaged",
--         conflict = get_icon "GitConflict",
--       },
--     },
--   },
--   window = {
--     width = 45,
--     position = "float",
--     mappings = {
--       ["<space>"] = false, -- disable space until we figure out which-key disabling
--       l = false,
--       ["[b"] = "prev_source",
--       ["]b"] = "next_source",
--       F = utils.is_available("telescope.nvim", false, false) and "find_in_dir" or nil,
--       O = "system_open",
--       Y = "copy_selector",
--       h = "parent_or_close",
--       u = "child_or_open",
--       o = "open",
--       ["?"] = "show_help",
--     },
--     fuzzy_finder_mappings = { -- define keymaps for filter popup window in fuzzy_finder_mode
--       ["<C-k>"] = "move_cursor_down",
--       ["<C-l>"] = "move_cursor_up",
--     },
--   },
--   -- commands = global_commands,
--   filesystem = {
--     follow_current_file = { enabled = true },
--     hijack_netrw_behavior = "open_current",
--     use_libuv_file_watcher = true,
--   },
--   event_handlers = {
--     -- {
--     --   event = "neo_tree_buffer_enter",
--     --   handler = function(_) vim.opt_local.signcolumn = "auto" end,
--     -- },
--     {
--       event = "file_opened",
--       handler = function(_)
--         require("neo-tree.command").execute({ action = "close" })
--       end
--     },
--   },
-- }
--
-- return {
--   "nvim-neo-tree/neo-tree.nvim",
--   tag = "3.39.0",
--   dependencies = {
--     { "nvim-lua/plenary.nvim" },
--     { "nvim-tree/nvim-web-devicons" },
--     { "MunifTanjim/nui.nvim",       tag = "0.4.0" },
--   },
--   config = function()
--     require("neo-tree").setup(setup)
--     vim.cmd([[nnoremap \ :Neotree reveal<cr>]])
--   end,
-- }
